### ISSUE TITLE
make project address go to project status

### ISSUE THREAD

**Issue by zivry** [codeine-cd/codeine#109]
http://codeine.intel.com:12347/codeine/project/tracker
to redirect to 
http://codeine.intel.com:12347/codeine/project/tracker/status

that makes navigation with address bar easier. 
currently displays an error page.

**Comment by zivry** [comment]
This is broken again 
http://codeine.intel.com:12347/codeine/view/main/project/tracker/
does not point to
http://codeine.intel.com:12347/codeine/view/main/project/tracker/status
probably due to another issue being fixed

**Comment by oshai** [comment]
fixed. commited by mistake on issue #107
