### ISSUE TITLE
Green V check mark is gone when a collector is set

### ISSUE THREAD

**Issue by koren99** [codeine-cd/codeine#125]
Why did you remove the Green V when the collectors are available, 
I still have monitors there. 
Can we keep the V and the custom collectors?

**Comment by oshai** [comment]
If a monitor will fail you will see it in red (in addition to other values). the green V is just not needed there. agree?

**Comment by koren99** [comment]
well... i figured that's the case, but it make the UI very non-symetric.​
since some items have a collector and some don't.
that's the feedback i got back from others. i'll pass your notes. :-)

**Comment by oshai** [comment]
ok, ask some more people.
