### ISSUE TITLE
lag between data collection for monitors/collectors and view

### ISSUE THREAD

**Issue by koren99** [codeine-cd/codeine#127]
When you access the collector manually, you see it ran at the current minute, but the main screen values are not updated. it takes a considerable amount of time to see the change reflected.

It sometime looks absurd, because during a patch, you can actually see the value inside the monitor as exit code 0 and the status in the table view, as failing.

so i'm starting out of a place where before i trust a monitor, i double check it's exit status and output because i don't trust the main view...

**Comment by oshai** [comment]
This is because we have many peers (not in your project). one alternative is that you will have a dedicated server.

**Comment by koren99** [comment]
i still don't get it. the callbacks are ajax. and the data is already
available (clearly, since i see it when i click on the specific collector
manually)
just the main view does not show the same values as the last collector log
view.

i don't see how it's related to the server's busyness...

if all data in all views was delayed then i'd say you are right, but that
is not the case.
