### ISSUE TITLE
Monitors stopped working on itstl1069

### ISSUE THREAD

**Issue by duduamar** [codeine-cd/codeine#152]
klil -3 shows:

========================>>>   Starting codeine peer at version 1.1.1054.4813    <<<========================
========================>>>   Starting with arguments: [-Xdebug, -Xrunjdwp:transport=dt_socket,server=y,suspend=n, -Xmx100m, -Dlog.dir=/var/log
/codeine]

Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "RunMonitors_codeine_itstl1069.iil.intel.com:_usr_co
deine_run_current_project_codeine"

Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "RunMonitors_wsms_nbdev_unstable_itstl1069.iil.intel
.com"

**Comment by oshai** [comment]
this is an old build. it was already fixed.
