### ISSUE TITLE
restart pool master command failed on sc_start

### ISSUE THREAD

**Issue by duduamar** [codeine-cd/codeine#155]
http://codeine.intel.com:12347/codeine/view/main/project/design_pool_masters/command/restart/73/status

running command 'restart' on 1 node by damar
nodes list: sc_start
===> executed on node: sc_start, output below <===
credentials = root
$ /bin/sh -xe /tmp/codeine_1077739338.sh
+ ../pool_masters_lib_standard/restart_standard.pl
will retart the pool
type is PPM
Stopping pool master with /nfs/site/gen/adm/netbatch/binaries/stopPoolMaster
executing: /nfs/site/gen/adm/netbatch/binaries/stopPoolMaster
[scynbm24]
==>  scynbm24: A term message has been sent to MATBATCH on this machine
==>  scynbm24: A term message has been sent to MAITRD on this machine

executing: /nfs/site/gen/adm/netbatch/binaries/nbadmin pool status --ta localhost 2>&1 | /usr/bin/head -15
Starting Pool Master with /nfs/site/gen/adm/netbatch/binaries/startPoolMaster 
executing: /nfs/site/gen/adm/netbatch/binaries/startPoolMaster 
Starting Pool Master.
Startup sequence is being logged to /var/netstar/log/PoolMaster.scynbm24.startup.
Pool Master is started
executing: /nfs/site/gen/adm/netbatch/binaries/nbadmin pool status --ta localhost 2>&1 | /usr/bin/head -15
===> error in node sc_start message: Premature EOF <===
finished!
failed nodes: sc_start
=========> aggregate-command-statistics (success/total): 0/1

The pool was restarted successfully, it was just the command appeared as failed.

**Comment by oshai** [comment]
It looks like something (external) killed the peer. the logs are only from a later time now, so I am closing it. let me know if you see it again.
