### ISSUE TITLE
AND/OR toggle in tags filtering

### ISSUE THREAD

**Issue by duduamar** [codeine-cd/codeine#163]
Today when selecting multiple tags it uses OR relation. We need a toggle to switch between OR and AND.

**Comment by ezraroi** [comment]
+1

**Comment by oshai** [comment]
I'm afraid it will not be intuitive in the ui. It was and in the past.

**Comment by ezraroi** [comment]
It is a real use case, sometimes you want to slice your data in different ways. We can make clear I think, and have the most common option to be the default one (the or)
