### ISSUE TITLE
Exception thrown when peer not found in DB when running command

### ISSUE THREAD

**Issue by ezraroi** [codeine-cd/codeine#173]
The command is canceled as the exception is thrown in the web server.
Should return null instead of throwing exception

**Comment by ezraroi** [comment]
https://github.com/codeine-cd/codeine/commit/8401d9e2513b2d3ad9193b1607650b819e55eae7

**Comment by oshai** [comment]
A suggestion: return guava Optional instead of returning null. ask @zivry
for details.
