### ISSUE TITLE
Pool access

### ISSUE THREAD

**Issue by a8ksh4** [codeine-cd/codeine#183]
Hi Codeine Team,

Sorry if this is the wrong place to ask...  How can I request access to see the fm_fpga wsm page?  I support all of the fpga and emulation nb pools, and should have access to all of them in the codeine page.  In particular, I cannot see the wsms_fm_fpga or wsms_iil_fpga links at http://codeine.intel.com:12347/codeine/view/wsm.

Thanks!
--Dan
EC Emulation

**Comment by ezraroi** [comment]
Hi, send me a mail to Roi, Ezra or open an HSD ticket. Here we track bugs
