### ISSUE TITLE
Monitor not sending notification 

### ISSUE THREAD

**Issue by ezraroi** [codeine-cd/codeine#186]
If the monitor fails on the first time it is running,  it will not send notification no matter the mail policy

**Comment by zivry** [comment]
That was a feature.
Tell me, who is code reviewing all this stuff?

**Comment by ezraroi** [comment]
I hope you will :)
Why it was a feature? If i have monitor defined with immediately mail police and it is failing since day one... i will never get an email on it

**Comment by oshai** [comment]
I am not sure how it was and what you changed, but if you want to get mail
on first failure you will get a mail in each codeine peer restart.

**Comment by ezraroi** [comment]
We no longer restarts the peers for updating the scripts... no we had monitors failing for day 1 without any notification

**Comment by oshai** [comment]
ok, are you reading all those mails :-)?

**Comment by ezraroi** [comment]
I am not,  but eyal is using it start for monitoring all the servers so they read them
