### ISSUE TITLE
Please grant me (jselam) access to manage the gdc_vp (design) pool

### ISSUE THREAD

**Issue by jselam** [codeine-cd/codeine#192]
As an Austin NB admin, I also provide support for the Netbatch service/pools in the Guadalajara (GM, ZPN) site.
Codeine is not giving me access to run any commands on the gdc_vp pool (master gmsmed03.zpn.intel.com), and I need to upgrade its software version.
Please give me the access.
-Jeff E

**Comment by ezraroi** [comment]
Done, you can send me an email if you have permissions requests. The github page is for development issues
